name = "Kwaterniony"
uuid = "6c78c1c9-f868-449c-9116-0508040774ee"
authors = ["Łukasz Kołaczek", "Michał Nawłoka", "Daria Szefer"]
version = "1.0.0-DEV"

[compat]
julia = "1.12.6"
StaticArrays = "v1.9.18"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
